title: "Suvojit Hazra<br>Ph.D. (Science)"
logo: assets/img/CV3.jpg
description: "ğŸ“ Suvojit with duck-billed dinosaur (Edmontosaurus) at UWâ€“Madison Geology Museum. <br>ğŸ“§ shazra3@wisc.edu"
show_downloads: false
theme: jekyll-theme-minimal
